language: node_js
node_js:
  - "12.13.0"
branches:
  only:
    - develop
install:
  - . scripts/install.sh
script:
  - . scripts/test.sh && . scripts/script.sh
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: TheSubliminal/mover
      branch: develop
    bucket: movers3
    region: us-west-2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: movers3
    key: latest.zip
    bundle_type: zip
    application: mover
    deployment_group: mover_deployment_group
    region: us-west-2
    on: *2
