version: '3'
services:
  client:
    build: ./client
    environment:
      - REACT_APP_MAPBOX_ACCESS_TOKEN=${REACT_APP_MAPBOX_ACCESS_TOKEN}
      - REACT_APP_GOOGLE_MAPS_TOKEN=${REACT_APP_GOOGLE_MAPS_TOKEN}
    volumes:
      - built-client:/mover/client/build
    command: echo 'built'

  server:
    build: ./server
    expose:
      - "${PORT}"
    environment:
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
      - IMGUR_ID=${IMGUR_ID}
      - IMGUR_SECRET=${IMGUR_SECRET}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - built-client:/mover/client/build
      - ./server/src:/mover/server/src
    depends_on:
      - client
      - postgres
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm run migrate && npm run seed && npm start'

  postgres:
    image: postgres:11
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./scripts/install-pgcrypto.sh:/docker-entrypoint-initdb.d/install-pgcrypto.sh
volumes:
  built-client:
